### PR TITLE
+ Add border-radius reset for Chrome on Mac

### PR DESCRIPTION
**Pull request by vseguin**

### CODE REVIEW

**Comment by MichelML** [comment]
next time you can add Germain and Mik to the reviewers and post a screen shot of what it does before/after to help us understand, although it is simple I know.

**Comment by MichelML** [comment]
I think you should use the $border-radius variable if you can @vseguin , this is the radius utilized in the btn.scss file. I might be wrong though others could confirm.

**Comment by GermainBergeron** [comment]
@MichelML In this case we shouldn't use the variable because thats not how it was by default and we don't want to cause more issues

**Comment by MichelML** [comment]
alright @GermainBergeron

**Pull request merged**
